# http://docs.travis-ci.com/user/languages/go/
language: go

go: 1.11.1

os:
  - linux

env:
  global:
    - GIT_LFS_SRC_DIR="$HOME/src/git-lfs"
    - GIT_LFS_TEST_DIR="$HOME/git-lfs-tests"
    - GIT_SOURCE_REPO="https://github.com/git/git.git"
    - GIT_EARLIEST_SUPPORTED_VERSION="v2.0.0"
    - GIT_LATEST_SOURCE_BRANCH="master"
    - GIT_ASKPASS=""

matrix:
  fast_finish: true
  include:
    - env: git-latest-master-from-source
      os: linux
      before_script:
        - >
          cd "$GIT_LFS_SRC_DIR";
          git clone $GIT_SOURCE_REPO git-source;
          cd git-source;
          git checkout $GIT_LATEST_SOURCE_BRANCH;
          make --jobs=2;
          make install;
          cd ..;
    - env: git-earliest-supported-version-from-source
      os: linux
      before_script:
        - >
          cd "$GIT_LFS_SRC_DIR";
          git clone $GIT_SOURCE_REPO git-source;
          cd git-source;
          git checkout $GIT_EARLIEST_SUPPORTED_VERSION;
          make --jobs=2;
          make install;
          cd ..;
    - env: git-latest
      os: linux
      addons:
        apt:
          sources:
          - git-core
          packages:
          - git

before_install:
  - >
    mkdir -p "$(dirname "$GIT_LFS_SRC_DIR")";
    mv "$TRAVIS_BUILD_DIR" "$GIT_LFS_SRC_DIR";
    export TRAVIS_BUILD_DIR="$GIT_LFS_SRC_DIR";

install: true

script: script/cibuild

notifications:
  email: false
