skip_branch_with_pr: true

environment:
  GOPATH: $(HOMEDRIVE)$(HOMEPATH)\go
  MSYSTEM: MINGW64

clone_folder: $(GOPATH)\src\github.com\git-lfs\git-lfs

install:
  - rd C:\Go /s /q
  - appveyor DownloadFile https://storage.googleapis.com/golang/go1.8.windows-amd64.zip
  - 7z x go1.8.windows-amd64.zip -oC:\ >nul
  - C:\go\bin\go version
  - cinst InnoSetup -y
  - refreshenv

build_script:
  - bash --login -c 'GOARCH=386 script/bootstrap'
  - mv bin\git-lfs.exe git-lfs-x86.exe
  - bash --login -c 'GOARCH=amd64 script/bootstrap'
  - mv bin\git-lfs.exe git-lfs-x64.exe

after_build:
  - iscc script\windows-installer\inno-setup-git-lfs-installer.iss

test_script:
  - bash --login script/cibuild

artifacts:
  - path: git-lfs-x86.exe
  - path: git-lfs-x64.exe
  - path: git-lfs-windows-*.exe
