[application]

name = "git-lfs"
version = "0.5.3"
authors = [
  "Rick Olson <technoweenie@gmail.com>",
  "Scott Barron <rubyist@github.com>",
]

[dependencies]

"github.com/cheggaaa/pb"                        = "bd14546a551971ae7f460e6d6e527c5b56cd38d7"
"github.com/kr/pretty"                          = "088c856450c08c03eb32f7a6c221e6eefaa10e6f"
"github.com/kr/pty"                             = "5cf931ef8f76dccd0910001d74a58a7fca84a83d"
"github.com/kr/text"                            = "6807e777504f54ad073ecef66747de158294b639"
"github.com/olekukonko/ts"                      = "ecf753e7c962639ab5a1fb46f7da627d4c0a04b8"
"github.com/rubyist/tracerx"                    = "d7bcc0bc315bed2a841841bee5dbecc8d7d7582f"
"github.com/spf13/cobra"                        = "864687ae689edc28688c67edef47e3d2ad651a1b"
"github.com/spf13/pflag"                        = "463bdc838f2b35e9307e91d480878bda5fff7232"
"github.com/technoweenie/assert"                = "b25ea301d127043ffacf3b2545726e79b6632139"
"github.com/technoweenie/go-contentaddressable" = "38171def3cd15e3b76eb156219b3d48704643899"
